Converters Unit Tests
mdemii/NetCoreRestAPI pull request #15
Opened 2020-09-11 07:03 UTC by zinkoviktor

2020-09-11 07:09 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/ConvertersTests/CategoryModelConverterConvertFrom.cs
> +        List<CategoryModel> categoryModels;
private members

2020-09-11 07:11 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/ConvertersTests/CategoryModelConverterConvertFrom.cs
> +            categoryModel = new CategoryModel()
use local variables

2020-09-11 07:15 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/ConvertersTests/CategoryModelConverterConvertFrom.cs
> +            // Arrange
use local variable for model instance

2020-09-11 07:15 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/ConvertersTests/CategoryModelConverterConvertFrom.cs
> +        public void CorrectClassTypeConvertedToCategoryEntity()
Name best practices

2020-09-11 07:22 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/ConvertersTests/CategoryModelConverterConvertFrom.cs
> +        public void CorrectClassTypeConvertedToCategoryEntityCollection()
name best practices

2020-09-18 07:17 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/BaseComparer.cs
> +        public int Compare(object x, object y)
Give full name for x, y

2020-09-18 07:23 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertFrom.cs
> +        public void AllItemsAreNotNull()
Use _ as space between words

2020-09-18 07:25 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertFrom.cs
> +    public class ConvertFrom
Use name CategoryModelConverter_ConverFrom_Test

2020-09-18 07:29 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertFrom.cs
> +            static bool predicate(CategoryEntity entity1, CategoryEntity entity2) =>
Refactor this into private filed

2020-09-18 07:37 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertFrom.cs
> +                categoryModel, categoryModel2
use only new CategoryModel instead variables

2020-09-18 07:37 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertFrom.cs
> +            var expected = new List<CategoryEntity> { categoryEntity, categoryEntity2 };
the same use only new CategoryEntity instead variables

2020-09-18 07:39 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertTo.cs
> +    public class ConvertTo
the same - rename class name

2020-09-18 07:42 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/DataLayer.EF/Converters/CategoryModelConverterTests/ConvertTo.cs
> +            static bool predicate(CategoryModel model1, CategoryModel model2) =>
refactor to private filed

2020-09-18 07:44 UTC, mdemiy requested changes
Fix comments

2020-09-25 07:19 UTC, mdemiy commented on NetCoreRestApi/tests/UnitTests/Helpers/BaseComparer.cs
> +                return -1;
Magic number, create constants

2020-09-25 07:40 UTC, mdemii approved these changes

2020-09-25 07:40 UTC, merged