Controllers tests, DI, Test Helpers
mdemii/NetCoreRestAPI pull request #17
Opened 2020-10-15 20:43 UTC by zinkoviktor

2020-10-16 07:06 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/Helpers/BaseComparer.cs
> +            for (var i = 0; i < list1.Count; i++)
rename i into index. Read code convention

2020-10-16 07:11 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/Helpers/CategoryHelpers/CategoryDtoHelper.cs
> +        }
vertical align under Istance

2020-10-16 07:12 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/Helpers/CategoryHelpers/CategoryDtoHelper.cs
> +        public static List<CategoryDto> GetCategoryDtos()
Move this to each test

2020-10-16 07:15 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/Helpers/CategoryHelpers/CategoryModelHelper.cs
> +    public class CategoryModelHelper : BaseComparer<CategoryModel>
Rename helper into comparer

2020-10-16 07:19 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/Helpers/ObjectPropertiesComparer.cs
> +    public static class ObjectPropertiesComparer
Remove this class

2020-10-16 07:21 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/Helpers/Tests/PerformanceTests.cs
> +    public class PerformanceTests
Remove

2020-10-16 07:25 UTC, mdemii commented on NetCoreRestApi/tests/UnitTests/WebApi/Controllers/ProductsControllerTests.cs
>          public void ProductsController_Get_ReturnsCategoryDtosList()
Rename ProductsController_Get_ReturnsCategoryDtosList into Get_Action_Test

2020-10-16 07:28 UTC, mdemii requested changes
Fix comments

2020-10-18 19:03 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/Helpers/BaseComparer.cs
> +            for (var i = 0; i < list1.Count; i++)
fixed

2020-10-18 19:04 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/Helpers/CategoryHelpers/CategoryDtoHelper.cs
> +        }
fixed

2020-10-18 19:04 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/Helpers/CategoryHelpers/CategoryDtoHelper.cs
> +        public static List<CategoryDto> GetCategoryDtos()
fixed

2020-10-18 19:04 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/Helpers/CategoryHelpers/CategoryModelHelper.cs
> +    public class CategoryModelHelper : BaseComparer<CategoryModel>
fixed

2020-10-18 19:05 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/Helpers/ObjectPropertiesComparer.cs
> +    public static class ObjectPropertiesComparer
fixed

2020-10-18 19:05 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/Helpers/Tests/PerformanceTests.cs
> +    public class PerformanceTests
removed

2020-10-18 19:10 UTC, zinkoviktor commented on NetCoreRestApi/tests/UnitTests/WebApi/Controllers/ProductsControllerTests.cs
>          public void ProductsController_Get_ReturnsCategoryDtosList()
renamed

2020-10-18 19:11 UTC, zinkoviktor commented
All comments resolved

2020-10-22 18:23 UTC, merged